before_all do
    ensure_git_branch(
        branch: "fastlane"
    )
    #ensure_git_status_clean
end

platform :android do
    desc "Build and release a new beta version"
    lane :beta do
        # Increment the version code
        increment_version_code(
            gradle_file_path: "./android/app/build.gradle"
        )
        # Increment the version name
        increment_version_name(
            gradle_file_path: "./android/app/build.gradle"
        )
        # Commit the version
        git_commit(
            path: "./android/app/build.gradle",
            message: "Version bump"
        )
        # Build your Android app
        gradle(task: "clean", project_dir: "./android")
        gradle(task: "bundle", build_type: "Release", project_dir: "./android")
     
    end
end